# Generated by Django 2.2 on 2021-07-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksapp', '0003_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='fakemanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
