# Generated by Django 2.2 on 2021-07-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksapp', '0004_fakemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fakemanager',
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_who_liked', to='favbooksapp.User'),
        ),
    ]
